//
// Generated by JTB 1.3.2
//

import java.util.*;
import syntaxtree.*;
import visitor.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class visitor_pass2<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   // 
   String INT = "int";
   String INTARRAY = "intarray";
   String BOOL = "boolean";
   String PEXP = "Primexp";
   String TYPEREQ = "Typereq";
   boolean imported_Function = false;

   HashMap<String,String> curr_lam_args = new HashMap<>();

   public HashMap<String,ClassInfo> classes = new HashMap<>();
   
   public String curr_class_name = null;
   public String curr_method_name = null;

   public boolean is_lambda(String str){
      return str.startsWith("Function");
   }

   public String lambda_type1(String str){
      String temp = "";
      if(str.startsWith("Function<")){
         int i = str.indexOf(",");
         temp = str.substring(9,i);
      }
      return temp;
   }

   public String lambda_type2(String str){
      String temp = "";
      if(str.startsWith("Function<")){
         int i = str.indexOf(",");
         temp = str.substring(i+1,str.length()-1);
      }
      return temp;
   }

   public boolean match_method_args(ArrayList<Variable> args,ArrayList<String> passed_arg_types){
      
      for(int i = 0;i < passed_arg_types.size();i++){
         if(!type_match(args.get(i).type,passed_arg_types.get(i))) return false;
      }
      return true;

   }

   public boolean type_match(String t1,String t2){
      
      // System.out.println("type match called for "+t1+","+t2);
      if(t1 == null || t2 == null ) return false;
      if(t1.equals(t2)) return true;
      
      
      if(classes.containsKey(t1) && classes.containsKey(t2)){
         ClassInfo curr = classes.get(t2);
         String par_name = curr.parent;
         while(par_name != null){
            if(par_name.equals(t1)) return true;
             curr = classes.get(par_name);
             par_name = curr.parent;
         }  
      }

      return false;
   }

   boolean list_equals(ArrayList<Variable> a,ArrayList<Variable> b){

      if(a.size() != (b.size())) return false;

      for(int i = 0;i<a.size();i++){
         if(!a.get(i).type.equals(b.get(i).type))
            return false;
      }
      return true;
   }
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return (R)"got into pass2";
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;

      curr_class_name = n.f1.f0.toString();
      curr_method_name = "main";

      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      // n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      
      curr_class_name = n.f1.f0.toString();
      curr_method_name = null;
      
      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;

      // ClassInfo parent = classes.get(n.f3.f0.toString());
      // parent.children.add(n.f1.f0.toString());
      
      String par_name = n.f3.f0.toString();

      curr_class_name = n.f1.f0.toString();
      curr_method_name = null;

      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      // n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;

      curr_method_name = n.f2.f0.toString();
      Lambda_exp le = new Lambda_exp();
      String ret_exp_type = "";

      n.f0.accept(this, argu);
      String ret_type = (String)n.f1.accept(this, argu);

      // n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);

      String par_name = classes.get(curr_class_name).parent;
      while(par_name != null){
         ClassInfo par = classes.get(par_name);
         if(par.methods.containsKey(curr_method_name)){
            
            Method par_m = par.methods.get(curr_method_name);
            String type1 = par_m.return_type;

            Method m = classes.get(curr_class_name).methods.get(curr_method_name);
            
            if(!type_match(type1, ret_type) || !list_equals(m.arg_list_ordered, par_m.arg_list_ordered)){
               // System.out.println("par_m:"+par_name+","+par_m.name);
               // System.out.println("curr_m:"+curr_method_name);
               // System.out.println("par_args: "+par_m.arg_list_ordered.size()+par_m.arg_list_ordered);
               throw new TypeCheckException("Type error");
            }
         }
         par_name = par.parent;
      }

      if(is_lambda(ret_type)){
         // System.out.println("in return lambda type");
         le.arg_type = lambda_type1(ret_type);
         le.ret_type = lambda_type2(ret_type);
         ret_exp_type = (String)n.f10.accept(this, (A)le);
      }
      else ret_exp_type = (String) n.f10.accept(this,argu);

      n.f11.accept(this, argu);
      n.f12.accept(this, argu);

      if(!type_match(ret_type,ret_exp_type))
         throw new TypeCheckException("Type error");

      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
    //   R _ret=null;
      // System.out.println("in Type"+curr_class_name+","+curr_method_name);
      String type = (String) n.f0.accept(this, argu);
      // System.out.println("type matched is "+type);

      if(!type.equals(INT) && !type.equals(BOOL) && !type.equals(INTARRAY) && !is_lambda(type)){
         if(!classes.containsKey(type)){
            throw new TypeCheckException("Symbol not found");
         }
      }
      return (R)type;
    //   return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)INTARRAY;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
    //   R _ret=null;
      n.f0.accept(this, argu);
      return (R)BOOL;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
    //   R _ret=null;
      n.f0.accept(this, argu);
      return (R)INT;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      // n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      String arg_type = n.f2.f0.toString();
      String ret_type = n.f4.f0.toString();
      
      if(!classes.containsKey(arg_type)){
         if(arg_type.equals("Integer")) arg_type = INT;
         else  if(arg_type.equals("Boolean")) arg_type = BOOL;
         else{
            throw new TypeCheckException("Symbol not found");
         }
      }
      if(!classes.containsKey(ret_type)){
         if(ret_type.equals("Integer")) ret_type = INT;
         else if(ret_type.equals("Boolean")) ret_type = BOOL;
         else{
            throw new TypeCheckException("Symbol not found");
         }
      }

      return (R)("Function"+"<"+arg_type+","+ret_type+">");
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      String type_rhs;
      Lambda_exp lambda_exp = new Lambda_exp();
      
      String type_lhs = (String)n.f0.accept(this, (A)TYPEREQ);
      n.f1.accept(this, argu);
      
      if(is_lambda(type_lhs)){
         // System.out.println("type_lhs:"+type_lhs);
         lambda_exp.arg_type = lambda_type1(type_lhs);
         lambda_exp.ret_type = lambda_type2(type_lhs);
      }

      if(is_lambda(type_lhs)){
         type_rhs = (String) n.f2.accept(this, (A)lambda_exp);
      }
      else type_rhs = (String)n.f2.accept(this, argu);

      n.f3.accept(this, argu);

      boolean matched = false;
      
      // System.out.println("assignment statement: "+type_lhs+","+type_rhs);

      if(type_rhs.equals("this")) type_rhs = curr_class_name;

      if(type_lhs.equals(type_rhs)) matched = true;
      else{
         //check if rhs is subclass of lhs
         matched = type_match(type_lhs, type_rhs);
      }
      
      if(!matched)
         throw new TypeCheckException("Type error");
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String type1 = (String)n.f0.accept(this, (A)TYPEREQ);
      n.f1.accept(this, argu);
      String type2 =(String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String type3 = (String)n.f5.accept(this, argu);
      n.f6.accept(this, argu);

      if(!type1.equals(INTARRAY) || !type2.equals(INT) || !type3.equals(INT))
         throw new TypeCheckException("Type error");
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      if(!BOOL.equals(type))
         throw new TypeCheckException("Type error");
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type1 = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);

      if(!BOOL.equals(type1))
         throw new TypeCheckException("Type error");
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      if(!BOOL.equals(type))
         throw new TypeCheckException("Type error");

      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      if(type== null || !INT.equals(type))
         throw new TypeCheckException("Type error");
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      // System.out.println("in exp"+curr_class_name+","+curr_method_name);
      if(argu instanceof Lambda_exp){
         // System.out.println("with lambda exp");
         // System.out.println(((Lambda_exp) argu).arg_type + ((Lambda_exp) argu).arg + ((Lambda_exp) argu).ret_type);
         
         return n.f0.accept(this,argu);
      }
      
      return n.f0.accept(this, (A)TYPEREQ);
      // return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      //here argu is TYPEREQ
      Lambda_exp le = new Lambda_exp();
      // System.out.println("in (iden) -> exp");

      n.f0.accept(this, argu);
      
      if(argu instanceof Lambda_exp){
         le = (Lambda_exp)argu;
         // System.out.println(((Lambda_exp) argu).arg_type + ((Lambda_exp) argu).arg + ((Lambda_exp) argu).ret_type);
         if(le.arg_type == null)
            throw new TypeCheckException("Type error");
         le.arg = null;
         n.f1.accept(this,(A)argu);
         le.arg = n.f1.f0.toString();
         curr_lam_args.put(le.arg, le.arg_type);
      }
      else {

         throw new TypeCheckException("Type error");
         // n.f1.accept(this, (A)null);
      }

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String exp_type = (String)n.f4.accept(this, (A)le);

      if(type_match(le.ret_type,exp_type))
      {
         curr_lam_args.remove(le.arg);
         return (R)("Function<"+le.arg_type+","+le.ret_type+">");
      }  
      else 
         throw new TypeCheckException("Type error");

   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String) n.f2.accept(this, argu);
      
      if(type1== null || type2== null|| !BOOL.equals(type1) || !BOOL.equals(type2)) 
         throw new TypeCheckException("Type error");
      return (R)BOOL;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String) n.f2.accept(this, argu);
      
      if(type1== null || type2== null ||!BOOL.equals(type1) || !BOOL.equals(type2)) 
         throw new TypeCheckException("Type error");
      return (R)BOOL;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String) n.f2.accept(this, argu);
      if(type1== null || type2 == null || !type1.equals(INT) || !type2.equals(INT)) 
         throw new TypeCheckException("Type error");
      return (R)BOOL;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;
      String type1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);

      if(type1== null || type2== null||!type_match(type1, type2) && !type_match(type1, type2))
         throw new TypeCheckException("Type error");
      
      return (R)BOOL;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      // System.out.println(type1 + "," + type2);

      if(type1 == null || type2 == null ||!type1.equals("int") || !type2.equals("int")) 
         throw new TypeCheckException("Type error");
      return (R)INT;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      // System.out.println(type1 + "," + type2);

      if(type1 == null || type2 == null ||!type1.equals(INT) || !type2.equals(INT)) 
         throw new TypeCheckException("Type error");
      return (R)INT;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      // System.out.println(type1 + "," + type2);

      if(type1 == null || type2 == null || !type1.equals(INT) || !type2.equals(INT)) 
         throw new TypeCheckException("Type error");
      return (R)INT;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      // R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      // System.out.println(type1 + "," + type2);

      if(type1 == null || type2 == null ||!type1.equals(INT) || !type2.equals(INT)) 
         throw new TypeCheckException("Type error");
      return (R)INT;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String type1 = (String) n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String) n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      if(type1 == null || type2 == null || !type1.equals(INTARRAY) || !type2.equals(INT)) 
         throw new TypeCheckException("Type error");
      return (R)INT;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String type1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      if(!INTARRAY.equals(type1))
         throw new TypeCheckException("Type error");
      return (R)INT;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      ArrayList<String> passed_arg_types = new ArrayList<>();

      String cname = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      // n.f2.accept(this, null);
      n.f3.accept(this, argu);
      
      // n.f5.accept(this, argu);

      
      if(cname == null ||(!cname.equals("this") && !classes.containsKey(cname))){
         //check if cname is lambda variable

         if(is_lambda(cname)){ 
            if(n.f2.f0.toString().equals("apply")){
               String arg_type = lambda_type1(cname);
               String ret_type = lambda_type2(cname);
               
               real_args = new ArrayList<>();
               real_args.add(new Variable(null,arg_type));
               n.f4.accept(this, (A)passed_arg_types);
               if(passed_arg_types.size() != 1) 
                  throw new TypeCheckException("Type error");
               
               if(type_match(arg_type,passed_arg_types.get(0)))
                  return (R)ret_type;
               else 
                  throw new TypeCheckException("Type error");
            }
            else throw new TypeCheckException("Type error");
         }
         else if(cname!= null && cname.equals(INT)) throw new TypeCheckException("Type error");
         else if(cname!= null && cname.equals(BOOL)) throw new TypeCheckException("Type error");
         else throw new TypeCheckException("Symbol not found");
         
      }

      ClassInfo currc;
      if(cname.equals("this")) currc = classes.get(curr_class_name);
      else currc = classes.get(cname);
      
      String mname = n.f2.f0.toString();
      
      Method m = null;

      if(currc.methods == null || !currc.methods.containsKey(mname)){

         String parname = currc.parent;
         boolean found = false;
         while(parname != null){
            ClassInfo par = classes.get(parname);
            if(par.methods != null && par.methods.containsKey(mname)){
               found = true;
               m = par.methods.get(mname);
               break;
            }
            parname = par.parent;
         }
         if(!found) throw new TypeCheckException("Symbol not found");
      }
      else {
         if(currc.methods.containsKey(mname))
            m = currc.methods.get(mname);
         else 
            throw new TypeCheckException("Symbol not found");
      }

      
      real_args = m.arg_list_ordered;
      if(real_args == null) throw new TypeCheckException("Type error"); 

      n.f4.accept(this, (A)passed_arg_types);

      // System.out.println("method "+mname+" called with args "+passed_arg_types);

      boolean matched = true;
      if(m.arg_list_ordered.size() != passed_arg_types.size()) matched = false;
      else {
         matched = match_method_args(m.arg_list_ordered, passed_arg_types);
      }

      if(!matched) 
         throw new TypeCheckException("Type error");
      return (R)(m.return_type);
   }

   ArrayList<Variable> real_args = null;
   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      
      Lambda_exp le = new Lambda_exp();
      String type;
      ArrayList<String> passed_arg_types = (ArrayList) argu;
      int indx = passed_arg_types.size();
      
      if(real_args == null || real_args.size() <= indx) throw new TypeCheckException("Type error");

      if(real_args.get(indx).type != null && is_lambda(real_args.get(indx).type)){
         le.arg_type = lambda_type1(real_args.get(indx).type);
         le.ret_type = lambda_type2(real_args.get(indx).type);
         // System.out.println("in exp list with lambda type"+le.arg_type+","+le.ret_type);
         type = (String)n.f0.accept(this, (A)le);
      }
      else type = (String)n.f0.accept(this, argu);
      
      passed_arg_types.add(type);

      n.f1.accept(this, (A)passed_arg_types);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;

      Lambda_exp le = new Lambda_exp();
      String type;
      ArrayList<String> passed_arg_types = (ArrayList) argu;
      int indx = passed_arg_types.size();

      if(real_args.size() <= indx) throw new TypeCheckException("Type error");

      n.f0.accept(this, argu);
      if(real_args.get(indx).type != null && is_lambda(real_args.get(indx).type)){
         le.arg_type = lambda_type1(real_args.get(indx).type);
         le.ret_type = lambda_type2(real_args.get(indx).type);
         // System.out.println("in exp rest with lambda type"+le.arg_type+","+le.ret_type);
         type = (String)n.f1.accept(this, (A)le);
      }
      else type = (String)n.f1.accept(this, argu);
      passed_arg_types.add(type);
      
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      if(argu != null && argu instanceof String){
         String func  = (String)argu;
         // System.out.println("in pexp with func "+func);
      }
   
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)INT;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
    //   R _ret=null;
      n.f0.accept(this, argu);
      return (R)BOOL;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
    //   R _ret=null;
      n.f0.accept(this, argu);
      return (R)BOOL;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {

      if(n.f0.toString().equals("Integer")) return (R)INT;
      if(n.f0.toString().equals("Boolean")) return (R)BOOL;
      
      n.f0.accept(this, argu);
      
      String func = "";
      String final_type = "";
      Lambda_exp le = new Lambda_exp();

      if(argu instanceof String) func = (String)argu;

      boolean islam = (argu instanceof Lambda_exp);
      boolean isarg = false;
      if(islam){
         le = (Lambda_exp)argu;
         isarg = (le.arg!=null) && (le.arg.equals(n.f0.toString()));
      }

      if(islam && isarg){
            return (R)le.arg_type;
      }

      //if identifier matched for rule in primary exp we need to return the type of identifier
      
      if(func.equals(TYPEREQ) || islam) {
         // System.out.println(func);

         String var_name = n.f0.toString();
         ClassInfo currc = classes.get(curr_class_name);
         Method currm = null;
         if(curr_lam_args.containsKey(var_name)){
            return (R)curr_lam_args.get(var_name);
         }
         if(currc.methods != null) 
            currm = currc.methods.get(curr_method_name);

         if(currm != null && currm.arg_list.containsKey(var_name)) 
            final_type = (currm.arg_list.get(var_name).type);

         else if(currm!= null && currm.var_decl.containsKey(var_name)) 
            final_type = (currm.var_decl.get(var_name).type);
         
         else if(currc.variables.containsKey(var_name)) 
            final_type = (currc.variables.get(var_name).type);
         else {
            String parname = currc.parent;
            while(parname != null){
               ClassInfo par = classes.get(parname);
               if(par.variables.containsKey(var_name)) {
                  final_type = (par.variables.get(var_name).type);
                  break;
               }
               parname = par.parent;
            }
         }

         if(final_type.equals("")){
            if(islam){
               if( le.arg == null) return (R)final_type;
               else throw new TypeCheckException("Symbol not found");
            } 
            else{

               throw new TypeCheckException("Symbol not found");
            }   // throw new TypeCheckException("var "+var_name+" not defined"+curr_class_name+","+curr_method_name);
         }
         else{
           return (R) final_type;
         }
      }
      
      return (R)n.f0.toString();
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)curr_class_name;
      // return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String exp_type = (String)n.f3.accept(this, argu);
      
      n.f4.accept(this, argu);
      
      if(!INT.equals(exp_type))
         throw new TypeCheckException("Type error");
      return (R)INTARRAY;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      // R _ret=null;
      n.f0.accept(this, argu);
      // n.f1.accept(this, null);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      String name = n.f1.f0.toString();
      if(!classes.containsKey(name))
         throw new TypeCheckException("Type error");
      return (R)(name);
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String type = (String)n.f1.accept(this, argu);

      if(!BOOL.equals(type))
         throw new TypeCheckException("Type error");
      return (R)BOOL;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String type = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)type;
   }

}

class Lambda_exp{
   public String arg = null;
   public String arg_type = null;
   public String ret_type = null;

   public Lambda_exp() {}
   public Lambda_exp(String arg_type_i){
      this.arg_type = arg_type_i;
   }
}
