//
// Generated by JTB 1.3.2
//

import java.util.*;
import syntaxtree.*;
import visitor.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   String printlabel = "printlabel";
   
   String print_decr_sp(IntegerLiteral n){
      Integer stack_slots = Integer.parseInt(n.f0.toString());
      stack_slots *= 4;
      stack_slots += 12;
      System.out.println("sw $fp, -8($sp)");
      System.out.println("move $fp, $sp");
      System.out.println("sw $ra, -4($fp)");
      System.out.println("subu $sp, $sp, "+stack_slots);

      return stack_slots.toString();
   }

   void print_halloc(){
      System.out.println(".text\n.globl _halloc");
      System.out.println("_halloc:\nli $v0, 9");
      System.out.println("syscall");
      System.out.println("j $ra");
   }
   void print_print(){
       System.out.println(".text\n.globl _print");
      System.out.println("_print:\nli $v0, 1");
      System.out.println("syscall");
      System.out.println("la $a0, newl");
      System.out.println("li $v0, 4");
      System.out.println("syscall");
      System.out.println("j $ra");
   }
   void print_error(){
      System.out.println(".text\n.globl _error_func");
      System.out.println("_error_func:");
      System.out.println("\tli $v0, 4");
      System.out.println("\tla $a0, str_er \n\t syscall");
      System.out.println("\tli $v0, 10 \n\t syscall");
   }

   void print_newl_strerr(){
      System.out.println(".data\n.align 0");
      System.out.println("newl: .asciiz \"\\n\"");
      System.out.println(".data\n.align 0");
      System.out.println("str_er: .asciiz \"ERROR: abnormal termination\\n\"");
   }


   Integer curr_proc_args = 0;

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      System.out.println(".text \n .globl main \n main:");

      String stack_slots = print_decr_sp(n.f5);

      n.f2.accept(this, argu); //args

      n.f5.accept(this, argu); //stack_slots

      n.f8.accept(this, argu); //max_call_args

      n.f10.accept(this, argu);

      System.out.println("addu $sp, $sp, "+stack_slots);
      System.out.println("lw $fp -8($sp)");
      System.out.println("lw $ra -4($sp)");
      System.out.println("j $ra");
      
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);

      print_error();
      print_halloc();
      print_print();
      print_newl_strerr();

      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      n.f0.accept(this, (A)printlabel);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      
      System.out.println("\n.text \n .globl "+n.f0.f0.toString());

      n.f0.accept(this, (A)printlabel);

      String stack_slots = print_decr_sp(n.f5);

      curr_proc_args = (Integer)n.f2.accept(this, argu); //args

      n.f5.accept(this, argu); //stack_slots
      
      n.f8.accept(this, argu); //max_call_args

      n.f10.accept(this, null);
      n.f11.accept(this, argu);
      System.out.println("addu $sp, $sp, "+stack_slots);
      System.out.println("lw $fp -8($fp)");
      System.out.println("lw $ra -4($sp)");

      System.out.println("j $ra");
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, null);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("nop");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("jalr _error_func");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      
      String reg = (String)n.f1.accept(this, argu);
      String label = n.f2.f0.toString();

      System.out.println("beqz "+reg+", "+label);
      
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      System.out.println("b "+n.f1.f0.toString());
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;

      String r1 = (String)n.f1.accept(this, argu);
      String i = n.f2.f0.toString();
      String r2 = (String)n.f3.accept(this, argu);
      System.out.println("sw "+r2+", "+i+"("+r1+")");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      String r1 = (String)n.f1.accept(this, argu);
      String r2 = (String)n.f2.accept(this, argu);
      String i = n.f3.f0.toString();
      System.out.println("lw "+r1+", "+i+"("+r2+")");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   boolean isreg(String s){
      return s.startsWith("$");
   }

   public R visit(MoveStmt n, A argu) {
      R _ret=null;

      String reg = (String)n.f1.accept(this, argu);
      

      Node choice = n.f2.f0.choice;
      if(choice instanceof HAllocate){
         System.out.println("addu $sp, $sp, -12");
         System.out.println("sw $v0, 4($sp)");
         System.out.println("sw $a0, 8($sp)");

         n.f2.accept(this, argu);
         //__
         System.out.println("move "+reg+", "+"$v0");
         
         System.out.println("lw $a0, 8($sp)");
         System.out.println("lw $v0, 4($sp)");
         System.out.println("addu $sp, $sp, 12");
      }
      else if (choice instanceof BinOp) {
         n.f2.accept(this,(A)reg);

      }
      else{ //simplexp
         _ret = n.f2.accept(this,null);
         if(_ret instanceof Integer){
            System.out.println("li "+reg+", "+_ret.toString());
         }
         else{
            if(isreg((String)_ret))
               System.out.println("move "+reg+", "+_ret);
            else
               System.out.println("la "+reg+", "+_ret);
         }
      }
      
      _ret = null;
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      Node choice = n.f1.f0.choice;
      
      System.out.println("addu $sp, $sp, -12");
      System.out.println("sw $v0, 4($sp)");
      System.out.println("sw $a0, 8($sp)");

      if(choice instanceof Reg){
         String reg = (String)n.f1.accept(this,null);
         System.out.println("move $a0, "+reg);
      }
      else if (choice instanceof IntegerLiteral) {
         Integer i = (Integer)n.f1.accept(this,null);
         System.out.println("li $a0, "+i.toString());
      }
      System.out.println("jal _print");

      System.out.println("lw $v0, 4($sp)");
      System.out.println("lw $a0, 8($sp)");
      System.out.println("addu $sp, $sp, 12");

      return _ret;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public R visit(ALoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg = (String)n.f1.accept(this, argu);
      String sa = (String)n.f2.accept(this, argu);
      
      System.out.println("lw "+reg+", "+sa);
      
      return _ret;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public R visit(AStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String sa = (String)n.f1.accept(this, argu);
      String reg = (String)n.f2.accept(this, argu);
      
      System.out.println("sw "+reg+", "+sa);

      return _ret;
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public R visit(PassArgStmt n, A argu) {
      R _ret=null;

      Integer i = (Integer)n.f1.accept(this, argu);
      String reg = (String)n.f2.accept(this, argu);
      
      i-=1; //passarg is one based indexing
      i*=4;

      System.out.println("sw "+reg+", "+i.toString()+"($sp)");
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public R visit(CallStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String s = (String)n.f1.accept(this, argu);
      System.out.println("jalr "+s);
      return _ret;
   }

   /**
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      Node choice = n.f1.f0.choice;
      
      if(choice instanceof Reg){
         String reg = (String)n.f1.accept(this,null);
         System.out.println("move $a0, "+reg);
      }
      else if (choice instanceof IntegerLiteral) {
         Integer i = (Integer)n.f1.accept(this,null);
         System.out.println("li $a0, "+i.toString());
      }
      System.out.println("jal _halloc");
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String)n.f0.accept(this, argu);
      String r2 = (String)n.f1.accept(this, argu);
      
      String r1 = (String)argu;

      _ret = n.f2.accept(this,null);
      if(_ret instanceof Integer){
         System.out.println(op+" "+r1+", "+r2+", "+_ret.toString());
      }
      else{
         System.out.println(op+" "+r1+", "+r2+", "+_ret);  
      }

      _ret = null;
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   HashMap<String, String> convert = new HashMap<>() {{
      put("PLUS", "add");
      put("MINUS", "sub");
      put("TIMES","mul");
      put("DIV","div");
      put("NE","sne");
      put("LE","sle");
   }};
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      // System.err.println(n.f0.choice.toString());
      _ret = (R)(convert.get(n.f0.choice.toString()));
      return _ret;
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public R visit(SpilledArg n, A argu) {
      R _ret=null;

      Integer i = (Integer)n.f1.accept(this, argu);
      
      if(i<curr_proc_args-4){
         i*=4;
         _ret = (R)(i.toString()+"($fp)");
      }
      else{
         i*=4;
         _ret = (R)(i.toString()+"($sp)");
      }
      return _ret;
   }

   /**
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
      // return _ret;
   }

   /**
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    */
   public R visit(Reg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)("$"+n.f0.choice.toString());
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;

      n.f0.accept(this, argu);
      _ret = (R)((Integer)Integer.parseInt(n.f0.toString()));
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      if(argu!=null && argu.equals(printlabel)){
         System.out.println(n.f0.toString()+":");
      }
      _ret = (R)n.f0.toString();
      
      return _ret;
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public R visit(SpillInfo n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <SPILLED>
    *       | <NOTSPILLED>
    */
   public R visit(SpillStatus n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

}
