//
// Generated by JTB 1.3.2
//

import java.util.*;
import syntaxtree.*;
import visitor.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class pass2<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   String ASTORE = "ASTORE",SPILLEDARG = "SPILLEDARG",ALOAD = "ALOAD",MOVE = "MOVE",TEMP = "TEMP",nouse="nouse",PASSARG = "PASSARG",v0 = "v0",store = "store";
   public HashMap<String, Proctype> procedures;
   Proctype curr_proc;
   String[] reg_names = new String[]{
      "t0","t1","t2","t3","t4","t5","t6","t7","t8","t9",
      "s0","s1","s2","s3","s4","s5","s6","s7",
      "a0","a1","a2","a3"
   };

   void pass_args(NodeListOptional lst){
      
      for(int i = 0;i<Math.min(lst.size(), 4);i++){
         String reg = (String)lst.nodes.get(i).accept(this,null);

         System.out.println("MOVE "+reg_names[18+i]+" "+reg);
      }
      
      for(int i = 4;i<lst.size();i++){
         String reg = (String)lst.nodes.get(i).accept(this,null);
         System.out.println(PASSARG+" "+(i-3)+" "+reg);   
      }
   }


   void save_callee(){
      for(int i = 0;i<10;i++){
         Integer off = curr_proc.temp_store_sp + i;
         System.out.println(ASTORE+" "+SPILLEDARG+" "+off.toString()+" "+reg_names[i]);
      }
   }

   void load_callee(){
      for(int i = 0;i<10;i++){
         Integer off = curr_proc.temp_store_sp + i;
         System.out.println(ALOAD+" "+reg_names[i]+" "+SPILLEDARG+" "+off.toString());
      }
   }

   void save_caller(){
      Integer off = curr_proc.args <= 4 ?0 :curr_proc.args-4; 
      for(int i = 0;i<8;i++){
         System.out.println(ASTORE+" "+SPILLEDARG+" "+(off+i)+" "+reg_names[10+i]);
      }
   }

   void load_caller(){
      Integer off = curr_proc.args <= 4 ?0 :curr_proc.args-4; 
      for(int i = 0;i<8;i++){
         System.out.println(ALOAD+" "+reg_names[10+i]+" "+SPILLEDARG+" "+(off+i));
      }
   }

   void get_args(){
      for(Integer i =0;i<curr_proc.args;i++){
         Integer j = 4;
         Intervaltype it = curr_proc.intervals_map.get(TEMP+" "+i.toString());
         if(it == null){
            System.err.println(curr_proc.name+i.toString());
         }
         String loadfrom;
         if(i<4) loadfrom = reg_names[i+18];
         else {
            loadfrom = SPILLEDARG + " "+ (i-4);
            System.out.println(ALOAD+" v0 "+loadfrom);
            loadfrom = "v0";
         }

         if(it == null){}
         else if(it.reg != -1) System.out.println(MOVE+" "+reg_names[it.reg]+" "+loadfrom);
         else{
            System.out.println(ASTORE+" "+SPILLEDARG+" "+(curr_proc.sp+it.stack_loc)+" "+loadfrom);
         }
      }
   }

   boolean is_reg(String s){
      if(s == null || s.isEmpty()) return false;
      char c = s.charAt(0);
      return (c == 'a'|| c == 's' || c== 't'||c=='v');
   }

   boolean is_free_v0 = true;
   void free_v0(){
      is_free_v0 = true;
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }


   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;

      curr_proc = procedures.get("MAIN");
      System.out.println("MAIN [0] ["+ curr_proc.stack_slots +"] [" + curr_proc.max_call_args+"]");

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      System.out.println("END");
      System.out.println("//"+curr_proc.spill_stat+"\n");

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      n.f0.accept(this, (A)"printlabel");
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      String name = n.f0.f0.toString();
      curr_proc = procedures.get(name);

      System.out.println(name+" ["+curr_proc.args+"] [" + curr_proc.stack_slots + "] [" + curr_proc.max_call_args + "]");

      n.f4.accept(this, argu);

      System.out.println("//"+curr_proc.spill_stat+"\n");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, null);
      free_v0();
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("NOOP");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("ERROR");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      
      n.f0.accept(this, argu);
      String r = (String)n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // if(r.equals(nouse))
         System.out.println("CJUMP "+r+" "+curr_proc.name+"_"+n.f2.f0.toString());
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      System.out.println("JUMP "+curr_proc.name+"_"+n.f1.f0.toString());
      // n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String r2 = (String)n.f3.accept(this, argu);

      // if(!r2.equals(nouse) && !r1.equals(nouse))
         System.out.println("HSTORE "+r1+" "+n.f2.f0.toString()+" "+r2);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String r1 = (String)n.f1.accept(this, (A)store);
      String r2 = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      
      if( !r1.equals(nouse)){
         if(is_reg(r1))
            System.out.println("HLOAD "+r1+" "+r2+" "+n.f3.f0.toString());
         else{
            int stack_loc = Integer.parseInt(r1);
            System.out.println("HLOAD "+v0+" "+r2+" "+n.f3.f0.toString());
            System.out.println(ASTORE+" "+SPILLEDARG+" "+stack_loc+" "+v0);
         }
      }

      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      
      String r = (String)n.f1.accept(this, (A)store);
      String exp = (String)n.f2.accept(this, argu);
      if(!r.equals(nouse) && !exp.equals(nouse)){
         if(is_reg(r))
            System.out.println("MOVE "+r+" "+exp);
         else{
            int stack_loc = Integer.parseInt(r);
            System.out.println(MOVE+" "+v0+" "+exp);
            System.out.println(ASTORE+" "+SPILLEDARG+" "+(stack_loc)+" "+v0);
         }
      }
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String sexp = (String)n.f1.accept(this, argu);
      System.out.println("PRINT "+sexp);
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      
      _ret = n.f0.accept(this, argu);
      free_v0();
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      save_caller();
      get_args();
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String sexp = (String)n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      System.out.println("MOVE v0 "+sexp);
      load_caller();
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   //kall
   public R visit(Call n, A argu) {
      R _ret=null;
      save_callee();
      
      String sexp = (String)n.f1.accept(this, argu);
      pass_args(n.f3);
      // n.f3.accept(this, argu);

      System.out.println("CALL "+sexp);
      load_callee();
      return (R)"v0";
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String sexp = (String)n.f1.accept(this, argu);
      System.out.println("MOVE v1 "+sexp);
      System.out.println("MOVE v1 PLUS v1 4");
      sexp = "v1";
      _ret = (R)("HALLOCATE "+sexp);
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op = (String)n.f0.accept(this, argu);
      String r = (String)n.f1.accept(this, argu);
      String sexp = (String)n.f2.accept(this, argu);
      _ret = (R)(op+" "+r+" "+sexp);
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      _ret = (R)(n.f0.choice.toString());
      // n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
      // return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   //tea
   public R visit(Temp n, A argu) {
      R _ret=null;
      String temp = "TEMP "+n.f1.f0.toString();

      Intervaltype i = curr_proc.intervals_map.get(temp);
      if(i == null||(i.reg == -1 && i.stack_loc == -1)){
         return (R)nouse;
      }
      if(i.reg != -1){
         _ret = (R)(reg_names[i.reg]);
      }
      else{
         if(argu!=null && argu.equals("store")){
            _ret = (R)String.valueOf(i.stack_loc+curr_proc.sp);
         }
         else{
            String reg = v0;
            if(!is_free_v0) reg = "v1"; 
            else is_free_v0 = false;
            // System.err.println("in tea sp:"+curr_proc.sp);
            System.out.println(ALOAD+" "+reg+" "+SPILLEDARG+" "+(curr_proc.sp+i.stack_loc));
            _ret = (R)reg;
         }
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;

      String passed = (String)argu;
      if(passed != null && passed.equals("printlabel")){
         System.out.println(curr_proc.name+"_"+n.f0.toString());
      }
      _ret = (R)n.f0.toString();
      // n.f0.accept(this, argu);
      return _ret;
   }

}
