//
// Generated by JTB 1.3.2
//

import java.util.*;
import syntaxtree.*;
import visitor.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   
   String TEMP = "TEMP ";
   Integer line_num = 0;

   public HashMap<Integer, Blocktype> line_to_block = new HashMap<>();
   public HashMap<String,Integer> label_to_line = new HashMap<>();
   public HashMap<String,Proctype> procedures = new HashMap<>();

   Proctype curr_proc;
   Blocktype curr_block;

   void print(ArrayList<Blocktype> b){

      for (Blocktype block : b ){
         //  Blocktype block = entry.getValue();
            System.out.println("Line " + block.lnumber + ":");
            System.out.println("Name : "+ block.name);
            System.out.println("  lnumber        = " + block.lnumber);
            System.out.println("  next_lnumber   = " + block.next_lnumber);
            System.out.println("  jump_label     = " + block.jump_label);
            System.out.println("  next_block     = " + 
                (block.next_block != null ? block.next_block.lnumber : "null"));
            System.out.println("  jump_block     = " + 
                (block.jump_block != null ? block.jump_block.lnumber : "null"));
            System.out.println("  def_var        = " + block.def_var);
            System.out.println("  use_var        = " + block.use_var);
            System.out.println("  in_var         = " + block.in_var);
            System.out.println("  out_var        = " + block.out_var);
            System.out.println("-----------------------------------");
      }

   }

   void process_labels(){
      for(int i : line_to_block.keySet()){
         Blocktype b = line_to_block.get(i);

         if(b.jump_label != null){
            b.jump_block = line_to_block.get(label_to_line.get(b.jump_label));
            if(b.jump_label == null) System.out.println("No label is there");
         }
         if(b.next_lnumber != -1){
            b.next_block = line_to_block.get(b.next_lnumber);
         }
      }
   }

   void process_in_out(){
      
      for(Proctype p : procedures.values()){
         // System.err.println(p.name);
         for(Blocktype b:p.blocks){
            b.in_var.addAll(b.use_var);
         }
         p.blocks.get(p.blocks.size()-1).next_lnumber = -1;
         p.blocks.get(p.blocks.size()-1).next_block = null;
         p.blocks.get(p.blocks.size()-1).jump_block = null;
         p.blocks.get(p.blocks.size()-1).jump_label = null;

         while(true){
            int no_change = 0;
            for(Blocktype b : p.blocks){
               // Blocktype b = line_to_block.get(i);
               HashSet<String> in_var1 = new HashSet<>(b.in_var), out_var1 = new HashSet<>(b.out_var);

               if(b.next_block!=null){
                  b.out_var.addAll(b.next_block.in_var);
               }
               if(b.jump_block!=null){
                  b.out_var.addAll(b.jump_block.in_var);
               }

               HashSet<String> temp = new HashSet<>(b.out_var);
               temp.removeAll(b.def_var);
               b.in_var.addAll(temp);
               if(b.in_var.equals(in_var1) && b.out_var.equals(out_var1)) no_change++;
            }
            if(no_change == p.blocks.size()) break;
         }
      }
   }

   void process_liveranges(){
      for(Proctype p:procedures.values()){
         for(Blocktype b : p.blocks){
            for(String temp : b.def_var){
               if(!p.intervals_map.containsKey(temp)){
                  // if(temp.equals("TEMP 27")) {System.err.println("putting TEMP 5 "+b.lnumber);}
                  p.intervals_map.put(temp,new Intervaltype(temp,b.lnumber,b.lnumber));
               
               }
            }
            // for(String temp : b.def_var){
            //    if(!p.intervals_map.containsKey(temp)) 
            //       p.intervals_map.put(temp,new Intervaltype(temp,b.lnumber,b.lnumber));
            // }
            for(String temp : b.in_var){
               if(!p.intervals_map.containsKey(temp)){
                  System.err.println(b.lnumber+" "+p.name);
                  System.err.println(b.in_var);
                  System.err.println(b.out_var);
                  System.err.println(temp);
               }
               p.intervals_map.get(temp).end = b.lnumber;
            }
         }
         for(Intervaltype i : p.intervals_map.values()){
            p.intervals.add(i);
         }
      }
   }
   
   void linscan(){
      
      process_liveranges();
      for(Proctype p : procedures.values()){
         
         TreeSet<Integer> freeregs = new TreeSet<>();
         for(int i = 0;i<18;i++) freeregs.add(i);

         TreeSet<Intervaltype> active = new TreeSet<>(
            (a,b)->{
               if(a.temp.equals(b.temp)) return 0;
               if(a.end >= b.end) return 1;
               return -1;
            }
         );
         int curr_sp = 0;
         for(Intervaltype i : p.intervals){
            //expire old intervals
            if(i.end == i.start) continue;
            Iterator<Intervaltype> it = active.iterator();
            while (it.hasNext()) {
               Intervaltype j = it.next();
               if (j.end >= i.start)
                  break;
               it.remove();
               freeregs.add(j.reg);
            }
            if(freeregs.isEmpty()){
               Intervaltype spill = active.last();
               //spill at interval
               p.spill_stat = "SPILLED";
               if(spill.end > i.end){
                  i.reg = spill.reg;
                  spill.reg = -1;
                  spill.stack_loc = curr_sp;
                  curr_sp++;
                  active.remove(spill);
                  active.add(i);
               }
               else{
                  i.stack_loc = curr_sp;
                  curr_sp++;
               }
            }
            else{
               i.reg = freeregs.first();
               freeregs.remove(freeregs.first());
               active.add(i);
            }
         }  
         p.stack_slots+=curr_sp;
         int a = p.args - 4 > 0 ? p.args - 4 : 0;
         int b = p.max_call_args == -1 ? 0 : 10;
         if(!p.name.equals("MAIN")){
            p.stack_slots +=8;
            p.temp_store_sp = a+8;
         }
         
         p.sp = p.temp_store_sp+b;
         // System.err.println(p.name+" ff "+p.sp);
         p.stack_slots+=a+b;
         p.max_call_args = p.max_call_args == -1?0 : p.max_call_args; 
      }
   }


   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      

      Proctype p = new Proctype("MAIN");
      
      line_num = 1;

      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      curr_proc = p;

      procedures.put(p.name,p);
      // label_to_line.put("MAIN",line_num);
      line_to_block.put(line_num,b);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      
      process_labels();
      process_in_out();
      // print(procedures.get("LL_Start").blocks);
      // print(procedures.get("LS_Search").blocks);
      linscan();

      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;

      n.f0.accept(this, (A)"labelreq");
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;

      // n.f0.accept(this, (A)"labelreq");
      line_num ++;
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      b.name = n.f0.f0.toString();

      line_to_block.put(line_num, b);

      Proctype p = new Proctype(n.f0.f0.toString());

      curr_proc = p;
      p.args = Integer.parseInt(n.f2.f0.toString()); //p.args is int
      p.blocks.add(b);
      procedures.put(p.name,p);
      
      for(Integer i = 0;i<p.args;i++){
         b.def_var.add(TEMP+i.toString());
      }

      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, null);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      
      Blocktype b = new Blocktype(line_num);
      b.name = "ERROR_BLOCK";
      b.next_lnumber = -1;

      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);
      
      n.f0.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;

      line_num += 1;
      
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      b.jump_label = curr_proc.name +"_" + n.f2.f0.toString();
      b.use_var.add(TEMP+n.f1.f1.f0.toString());

      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;

      line_num += 1;
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = -1;
      b.jump_label = curr_proc.name +"_" + n.f1.f0.toString();

      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      
      line_num += 1;
      
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      b.use_var.add(TEMP+n.f1.f1.f0.toString());
      b.use_var.add(TEMP+n.f3.f1.f0.toString());

      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;

      line_num += 1;
      
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      b.def_var.add(TEMP+n.f1.f1.f0.toString());
      b.use_var.add(TEMP+n.f2.f1.f0.toString());

      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;

      line_num += 1;
      
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      b.def_var.add(TEMP+n.f1.f1.f0.toString());

      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      curr_block = b;

      n.f2.accept(this, argu);
      // System.err.println(b.use_var);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      line_num += 1;
      
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      
      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      
      line_num += 1;
      
      Blocktype b = new Blocktype(line_num);
      b.next_lnumber = line_num+1;
      curr_block = b;
      curr_proc.blocks.add(b);
      line_to_block.put(line_num,b);

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      
      curr_proc.max_call_args = Math.max(curr_proc.max_call_args, n.f3.size());
      n.f3.accept(this, (A)"templst");
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;

      curr_block.use_var.add(TEMP+n.f1.f1.f0.toString());
      
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, (A)"sexp");
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   //tt
   public R visit(Temp n, A argu) {
      R _ret=null;
      
      String passed = (String)argu;
      if(argu != null && (passed.equals("sexp")||passed.equals("templst"))){
         curr_block.use_var.add(TEMP+n.f1.f0.toString());
      }
      
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;

      String passed = (String)argu;
      if(argu != null && passed.equals("labelreq")){
         
         line_num++;
         Blocktype b = new Blocktype(line_num);
         b.next_lnumber = line_num+1;
         b.name = curr_proc.name+"_"+n.f0.toString();
         label_to_line.put(b.name, line_num);
         line_to_block.put(line_num,b);
         curr_proc.blocks.add(b);
      }
      n.f0.accept(this, argu);
      return _ret;
   }

}
