//
// Generated by JTB 1.3.2
//

import java.util.*;
import syntaxtree.*;
import visitor.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
class Variable{
   String temp = null;
   String type = null;
   String name = null;
   public Variable ( ){}
   public Variable ( String type,String name, String temp){
      this.name = name;
      this.temp = temp;
      this.type = type;
   }
}

public class pass2<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   String INTARRAY = "INTARRAY",INT = "INT",BOOL = "BOOL",FUNCTION = "Function"; 

   String MAIN = "MAIN \n";
   String BEGIN = "\nBEGIN \n", RETURN = "RETURN ", END = "\n END \n";
   String CJUMP = "CJUMP ", JUMP = "JUMP ", CALL = " CALL ";
   String HSTORE = "HSTORE ",HLOAD = "HLOAD ", HALLOCATE = "HALLOCATE ";
   String MOVE = "MOVE ";
   String PRINT = "PRINT ";
   String TEMP = "TEMP ";
   String NOOP = "NOOP \n", ERROR = "ERROR ";
   String LE = "LE ",NE = "NE ",PLUS = "PLUS ",MINUS = "MINUS ",TIMES = "TIMES ",DIV = "DIV ";
   String endl = "\n",space = " ";

   public HashMap<String,ClassInfo> classes;
   String curr_class_name,curr_method_name;

   Stack<HashMap<String,Variable>> scopes = new Stack<>();

   Stack<HashMap<String,String>> type_scope = new Stack<>();

   boolean in_type = false;

   Integer num = 100;

   String gen_temp(){
      num++;
      return (TEMP + num.toString()+" ");
   }
   Integer num_l = 0 ;
   String gen_label(){
      num_l++;
      return ("L"+num_l.toString()+"\n");
   }

   String entry_to_label(String entry){
      return entry.replaceFirst(" ", "_");
   }
   
   String get_name(String str){
      int idx = str.indexOf(" ");
      if(idx != -1)
         return str.substring(idx+1);
      return str;
   }

   Integer get_offset(ArrayList<String> ls,String str){

      if(ls.contains(curr_class_name+" "+str))
         return ls.indexOf(curr_class_name+" "+str);
      
      for(int i = ls.size() - 1 ;i>=0;i--){
         if(str.equals(get_name(ls.get(i))))
            return i;
      }
      return -1;
   }

   String get_type_var(ClassInfo c,String str){
      ArrayList<String> ls = c.variables;
      for(int i = ls.size() - 1 ;i>=0;i--){
         if(str.equals(get_name(ls.get(i))))
            return c.types_var.get(ls.get(i));
      }
      return null;
   }

   String get_type_meth(ClassInfo c,String str){
      
      ArrayList<String> ls = c.methods;

      for(int i = ls.size() - 1 ;i>=0;i--){
         if(str.equals(get_name(ls.get(i))))
            return c.types_meth.get(ls.get(i));
      }
      return null;
   }
   
   public void println_translation(String code){
      if(in_lambda == 0) System.out.println(code);
      else{
         lam_cls_stack.peek().apply += code + "\n";
         // curr_lambda_apply += code + "\n";
      }
   }

   public void print_translation(String code){
      if(in_lambda == 0) System.out.print(code);
      else{
         lam_cls_stack.peek().apply += code + "\n";
         // curr_lambda_apply += code;
      }
   }   

   public boolean is_lambda_type(String str){
      return str.startsWith("Function");
   }

   public String lambda_type1(String str){
      String temp = "";
      if(str.startsWith("Function<")){
         int i = str.indexOf(",");
         temp = str.substring(9,i);
      }
      return temp;
   }

   public String lambda_type2(String str){
      String temp = "";
      // System.err.println(curr_class_name+" "+curr_method_name+" "+str);
      if(str.startsWith("Function<")){
         int i = str.indexOf(",");
         temp = str.substring(i+1,str.length()-1);
      }
      return temp;
   }

   Integer num_for_lam = 0;
   int in_lambda = 0;
   String lambda_arg_type,lambda_ret_type;

   String gen_lambda_label(){
      num_for_lam++;
      return FUNCTION+"_"+num_for_lam.toString();
   }
   ArrayList<String> lambda_functions = new ArrayList<>();
   // String curr_lambda_apply = new String();

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      // System.err.println("lamda func size: "+lambda_functions.size());
      for(String str:lambda_functions){
         System.out.println(str);
      }
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      curr_class_name = n.f1.f0.toString();
      curr_method_name = "main";

      println_translation(MAIN);

      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      // n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);

      println_translation(END);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      curr_class_name = n.f1.f0.toString();
      curr_method_name = "";

      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      curr_class_name = n.f1.f0.toString();
      curr_method_name = "";

      n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      // n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      
      String var_name = n.f1.f0.toString();

      String type = (String)n.f0.accept(this, argu);

      if(!curr_method_name.isEmpty()){
          String temp = gen_temp();
         HashMap<String,Variable> curr_scope = scopes.peek();

         curr_scope.put(var_name,new Variable(type,var_name,temp));
      }
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      curr_method_name = n.f2.f0.toString();
      HashMap<String,Variable> new_scope = new HashMap<>();
      scopes.push(new_scope);

      n.f0.accept(this, argu);
      String ret_type = (String)n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      
      //f4 is arg_list;
      n.f4.accept(this, argu);
      
      //f7 vardecl
      n.f7.accept(this, argu);

      println_translation(curr_class_name+"_"+curr_method_name +" [ "+ arg_num.toString() + " ]");
      arg_num = 1;
      println_translation(BEGIN);

      //statements
      n.f8.accept(this, argu);

      println_translation(RETURN);

      if(is_lambda_type(ret_type)){
         lambda_arg_type = lambda_type1(ret_type);
         lambda_ret_type = lambda_type2(ret_type);
      }
      n.f10.accept(this, argu);

      println_translation(END);
      
      scopes.pop();

      return _ret;
   }

   Integer arg_num = 1;
   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      arg_num = 1;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      
      String var_name = n.f1.f0.toString();

      String type = (String)n.f0.accept(this, argu);
      if(!curr_method_name.isEmpty()){
         String temp = TEMP + arg_num.toString() + space;
         arg_num++;
         HashMap<String,Variable> curr_scope = scopes.peek();

         curr_scope.put(var_name,new Variable(type,var_name,temp));
      }
      // n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      in_type = true;
      _ret = n.f0.accept(this, argu);
      in_type = false;

      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)INTARRAY;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)BOOL;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)INT;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      // n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      String arg_type = n.f2.f0.toString();
      String ret_type = n.f4.f0.toString();

      if(arg_type.equals("Integer")) arg_type = INT;
      else  if(arg_type.equals("Boolean")) arg_type = BOOL;
      
      if(ret_type.equals("Integer")) ret_type = INT;
      else if(ret_type.equals("Boolean")) ret_type = BOOL;
      
      _ret = (R)(FUNCTION+"<"+arg_type+","+ret_type+">");
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;

      String iden = n.f0.f0.toString();

      HashMap<String,Variable> curr_scope = scopes.peek();
      
      if(curr_scope.containsKey(iden)){
         Variable v = curr_scope.get(iden);
         print_translation(MOVE + v.temp + " ");
         if(is_lambda_type(v.type)){
            lambda_arg_type = lambda_type1(v.type);
            lambda_ret_type = lambda_type2(v.type);
         }
      }
      else{
         ClassInfo c = classes.get(curr_class_name);
         Integer offset = get_offset(c.variables, iden);
         offset = offset*4;

         String fields = gen_temp();
         println_translation(HLOAD + fields + TEMP+ " 0 4 ");
         print_translation(HSTORE + fields + offset.toString() + " ");
      }

      // n.f0.accept(this, argu);
      n.f2.accept(this, argu);
      println_translation("");

      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String arr = gen_temp();
      String idx = gen_temp();
      String final_val;

      print_translation(MOVE + arr + " ");
         n.f0.accept(this, argu);
      
      print_translation(MOVE + idx);
         n.f2.accept(this, argu);
      
      println_translation(HSTORE + PLUS + arr + TIMES + PLUS + idx +  " 1 4 " + " 0 ");
         n.f5.accept(this, argu);
      println_translation("");
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      String code = "";
      String l1 = gen_label();
      println_translation(CJUMP + NE );
      n.f2.accept(this, argu);
      
      print_translation(" 0 "+l1);

      n.f4.accept(this, argu);
      
      println_translation(l1 + NOOP);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      
      String l0 = gen_label(),l1 = gen_label();

      print_translation(CJUMP + NE );
      n.f2.accept(this, argu);
      println_translation(" 0 " + l0);

      n.f4.accept(this, argu);
      println_translation(JUMP + l1);

      println_translation(l0 + NOOP);
      n.f6.accept(this, argu);
      println_translation(l1 + NOOP);

      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      String code = "";
      String l0 = gen_label(),l1 = gen_label();
      
      code += l0;
      
      code += CJUMP + NE;
      println_translation(code);code = "";
      n.f2.accept(this, argu);
      code += " 0 " + l1;

      println_translation(code);code = "";
      n.f4.accept(this, argu);
      code += JUMP + l0;

      code += l1 + NOOP + endl;
      println_translation(code);
      return _ret;
   }

   /**
    * f0 -> "println_translation"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      println_translation(PRINT);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
      // return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   //"lexp"
   
   Stack<lam_class> lam_cls_stack = new Stack<>();

   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      
      in_lambda++;
      String arg = n.f1.f0.toString();
      
      //have to add stack for following 3 fields also for handling nested lambdas
      lam_class curr_lam_cls = new lam_class();

      // curr_lambda_apply = new String();
      String new_obj = gen_temp();
      String label = gen_lambda_label();

      HashMap<String,Variable> curr_scope = scopes.peek();
      curr_scope.put(arg,new Variable(lambda_arg_type,arg,"TEMP -1"));

      // ArrayList<String> curr_obj_offset = new ArrayList<>();

      curr_lam_cls.obj_offset.add("vtable ");
      curr_lam_cls.obj_offset.add("this class point");

      curr_lam_cls.apply = label+" [ 2 ] \n";
      curr_lam_cls.apply += BEGIN + RETURN;

      lam_cls_stack.push(curr_lam_cls);

      // n.f1.accept(this, argu); //arg (identifier)
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      curr_lam_cls = lam_cls_stack.peek();
      ArrayList<String> curr_obj_offset = curr_lam_cls.obj_offset;
      curr_scope = scopes.peek();
      String code = "";
      Integer sz = (curr_lam_cls.obj_offset.size())*4;
      
      code += BEGIN;
         code += MOVE + new_obj + HALLOCATE + sz.toString()+endl;
         code += HSTORE + new_obj + " 0 " +  label + "\n";
         code += HSTORE + new_obj + " 4 " + " TEMP 0 " + "\n";
         
         for(int i = 2;i<curr_obj_offset.size();i++){
            String temp = curr_scope.get(curr_obj_offset.get(i)).temp;
            Integer j = i*4;
            code += HSTORE + new_obj + j.toString() + " " + temp + "\n";
         }
      code += RETURN + new_obj;
      code += END;

      curr_lam_cls.apply += END;

      lam_cls_stack.pop();
      curr_scope.remove(arg);
      lambda_functions.add(curr_lam_cls.apply);
      in_lambda--;

      println_translation(code);
      
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      String final_val = gen_temp();
      String l0 = gen_label();

      println_translation(BEGIN+MOVE+final_val);
      n.f0.accept(this, argu);

      println_translation(CJUMP + NE + final_val + "0 " + l0);

      println_translation(MOVE + final_val + TIMES + final_val);
      n.f2.accept(this, argu);
      
      print_translation(l0+NOOP);
      print_translation(RETURN + final_val + "\n" + END);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      String code = BEGIN;
      String v1 = gen_temp();
      String final_val = gen_temp();
      String l0 = gen_label();
      

      code += MOVE + final_val;
      println_translation(code);code = "";
      n.f0.accept(this, argu);
      
      code += CJUMP + NE + final_val + "1 " + l0;

      code += MOVE + final_val;
      println_translation(code);code = "";
      n.f2.accept(this, argu);

      code += l0 + NOOP;
      code += RETURN + final_val + "\n";
      code += END;
      print_translation(code);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      print_translation(LE);

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;
      print_translation(NE);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      R _ret=null;
      print_translation(PLUS);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      print_translation(MINUS);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      print_translation(TIMES);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      R _ret=null;

      print_translation(DIV);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String code = BEGIN;
      String arr = gen_temp();
      String idx = gen_temp();
      String val = gen_temp();
      
      code += MOVE + arr ;
      println_translation(code);code = "";
      n.f0.accept(this, argu);
      
      code += MOVE + idx ;
      println_translation(code);code = "";
      n.f2.accept(this, argu);

      code += MOVE + idx +TIMES + PLUS + idx + " 1 4\n";
      code += HLOAD + val + PLUS + arr + idx + " 0\n";
      code += RETURN + val + "\n";
      code += END;
     
      print_translation(code);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String code = BEGIN;
      String arr = gen_temp();
      String len = gen_temp();
      code += MOVE + arr ;
      println_translation(code);code = "";
      n.f0.accept(this, argu);

      code += HLOAD + len + arr + " 0\n";
      code += RETURN + len + "\n";
      code += END;

      println_translation(code);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   Boolean in_msgsend = false;
   public R visit(MessageSend n, A argu) {
      R _ret = null;

      in_msgsend = true;
      String obj = gen_temp();
      String vtable = gen_temp();
      String final_m = gen_temp();
      String m_name = n.f2.f0.toString();

      

      print_translation(CALL + BEGIN + MOVE + obj);    
      String type = (String)n.f0.accept(this, argu); //prim_exp()
      println_translation(endl);

      if(m_name.equals("apply")){
         println_translation(HLOAD +final_m+obj + " 0 ");
         println_translation(RETURN + final_m + END);
         println_translation("(" + obj);
                  n.f4.accept(this, argu); //explist passed as arguments
         print_translation(" )\n");
         // System.err.println("in msg send"+type+" ");
         return (R)lambda_type2(type);
      }

      ClassInfo c = classes.get(type);

      Integer offset = get_offset(c.methods, m_name);
      ArrayList<String> arg_types = c.meth_arg_types.get(type+" "+m_name);
      // System.err.println("in pxp"+arg_types);
      // System.err.println(type+" "+m_name);

      offset = offset*4;
      
      String code = HLOAD + vtable + obj + " 0\n";
             code +=  HLOAD + final_m + vtable + offset.toString() + " \n";
      
      code += RETURN + final_m + endl;
      code += END;
      code += "( " + obj ;

         println_translation(code);code = "";
         n.f4.accept(this, (A)arg_types); //explist passed as arguments

      print_translation(" )\n");

      String ret_type = get_type_meth(c, m_name);
      // System.err.println("in msg send + "+type+" "+ret_type);
      return (R)ret_type;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */

   int idx = 0;

   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      idx = 0;
      ArrayList<String> arg_types = new ArrayList<>();
      if(argu!=null)
         arg_types = (ArrayList<String>)argu;
      // System.err.println(idx);
      if(argu != null && is_lambda_type(arg_types.get(idx))){
         lambda_arg_type = lambda_type1(arg_types.get(idx));
         lambda_ret_type = lambda_type2(arg_types.get(idx));
      } 
      idx++;

      n.f0.accept(this, null);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      
      ArrayList<String> arg_types = new ArrayList<>();
      if(argu!=null)
         arg_types = (ArrayList<String>)argu;
      // System.err.println(idx);
      if(argu != null && is_lambda_type(arg_types.get(idx))){
         lambda_arg_type = lambda_type1(arg_types.get(idx));
         lambda_ret_type = lambda_type2(arg_types.get(idx));
      } 
      idx++;

      n.f0.accept(this, argu);
      n.f1.accept(this, null);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      return n.f0.accept(this, argu);
      // return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      
      print_translation(" "+n.f0.toString()+" ");
      
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      println_translation(" 1 ");
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      println_translation(" 0 ");
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   //"iden"
   public R visit(Identifier n, A argu) {
      R _ret=null;
      
      if(in_type){
         if(n.f0.toString().equals("Integer")) return (R)INT;
         if(n.f0.toString().equals("Boolean")) return (R)BOOL;
         return (R)n.f0.toString();
      }

      String iden = n.f0.toString();
      if(scopes == null){
         println_translation("scopes null "+curr_class_name + " ::" + curr_method_name);
         // throw new RuntimeException();
      }
      HashMap<String,Variable> curr_scope = scopes.peek();

      
      if(curr_scope.containsKey(iden)){
         
         Variable v = curr_scope.get(iden);
         
         //if its a lambda argument then it is in curr_scope with TEMP -1
         if(v.temp.equals("TEMP -1")){
            println_translation(TEMP+"1");
            return (R)v.type;
         }

         if(in_lambda == 0)
            print_translation(v.temp + " ");
         else{
            lam_class curr_lam_cls = lam_cls_stack.peek();
            ArrayList<String> lam_obj_offset = curr_lam_cls.obj_offset;
            Integer offset;
            String code = "";

            if(lam_obj_offset.contains(iden)) offset = lam_obj_offset.indexOf(iden);
            else{
               lam_obj_offset.add(iden);
               offset = lam_obj_offset.size() - 1;
            } 
            
            offset = offset*4;
            code += BEGIN;
               code += HLOAD + v.temp + TEMP + " 0 "+ offset.toString()+endl;
            code += RETURN + v.temp;
            code += END;
            println_translation(code);
         }
         return (R) v.type;
      }
      else {
         if(curr_method_name.isEmpty()) throw new RuntimeException();
         ClassInfo c = classes.get(curr_class_name);
         Integer offset = get_offset(c.variables, iden);

         offset = offset*4;

         String final_val = gen_temp();

         String this_pointer = " TEMP 0 ";
         if(in_lambda != 0) 
         {
            // System.err.println(iden+" "+offset+" "+curr_method_name);
            this_pointer = final_val;
         }

         String code = BEGIN;
            if(in_lambda!=0) code += HLOAD + final_val + " TEMP 0 4 \n";
            code += HLOAD + final_val + this_pointer + "4 \n";
            code += HLOAD + final_val + final_val + offset.toString() + space + "\n";   
            code += RETURN + final_val + endl;
         code += END;
         print_translation(code);

         String type = get_type_var(c, iden);
         
         // System.err.println("in iden+"+iden+" "+type);
         return (R)type;
      }

      // return (R)n.f0.toS//tring();
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      if(in_lambda == 0)
         print_translation(TEMP + " 0 ");
      else{
         String newt = gen_temp();
         print_translation(BEGIN + HLOAD + newt + "TEMP 0 4\n" + RETURN + newt + END );
      }
      return (R)curr_class_name;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;

      String code = BEGIN;

      String new_arr = gen_temp();

      String len = gen_temp();
      String org_len = gen_temp(); // afterwards we are making len = (len+1)*4
      //so for storing original length
      code += MOVE + len + " "; 
      
      println_translation(code);code = "";
      n.f3.accept(this, argu);
      
      code += MOVE + org_len + len + "\n";
      code += MOVE+ len +  TIMES + PLUS + len + " 1 4\n";
      code += MOVE + new_arr + HALLOCATE + len + "\n" ; 
      
      // store length at position 0
      code += HSTORE + new_arr + " 0 " + org_len + "\n";

      String l0 = gen_label(),l1 = gen_label();
      String k = gen_temp();

      code += MOVE + k + " 4\n";
      code+=l0;
      code += CJUMP + LE + k + MINUS + len + " 1 "+ l1;
         code += HSTORE + PLUS + new_arr + k + "0 0\n";
         code += MOVE + k + PLUS + k + "4\n";
      code += JUMP + l0;

      code += l1 + NOOP;
      code += RETURN + new_arr+endl;
      code += END;
      println_translation(code);

      return (R)INTARRAY;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      
      ClassInfo c = classes.get(n.f1.f0.toString());
      if(c == null){
         // System.err.println("kodaka ra");
      }
      Integer m_size = c.methods.size(),f_size = c.variables.size();
      m_size = m_size*4;
      f_size = f_size*4;

      String code = BEGIN;
      String new_obj = gen_temp();
      
      code += MOVE + new_obj + HALLOCATE+"8\n";

      String vtable = gen_temp();
      String fields = gen_temp();
      
      code += MOVE + vtable + HALLOCATE +(m_size).toString()+"\n";
      code += MOVE + fields + HALLOCATE + f_size.toString()+"\n";
      
      for(int i = 0;i<m_size/4;i++){
         Integer j = i*4;
         code += HSTORE + vtable + j.toString() + " "+ entry_to_label(c.methods.get(i))+"\n";
      }

      if(f_size != 0){
         String l1 = gen_label(),l0 = gen_label();
         String k = gen_temp();
         code += MOVE + k +" 0\n";
         f_size--;
         code += l0; 
         code += CJUMP + LE + k + f_size +" "+l1;
            code += HSTORE + PLUS + fields + k + " 0 0 \n";
            code += MOVE + k + PLUS + k + " 4 \n";
         code += JUMP + l0;

         code += l1;
      }
      code += HSTORE + new_obj + "0 " + vtable +endl;
      code += HSTORE + new_obj + "4 " + fields + endl;
      code += RETURN + new_obj+'\n';
      code += END;
      print_translation(code);

      // n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // n.f3.accept(this, argu);
      return (R)n.f1.f0.toString();
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      
      print_translation(MINUS + " 1 ");
      
      n.f1.accept(this, argu);
      
      return (R)BOOL;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return (R)n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // return _ret;
   }

}

class lam_class{
   ArrayList<String> obj_offset = new ArrayList<>();
   String apply = new String();
}
