//
// Generated by JTB 1.3.2
//

import java.util.*;
import syntaxtree.*;
import visitor.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class converter<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   String MAIN = "MAIN \n";
   String BEGIN = "\nBEGIN \n", RETURN = "RETURN ", END = "\n END \n";
   String CJUMP = "CJUMP ", JUMP = "JUMP ", CALL = " CALL ";
   String HSTORE = "HSTORE ",HLOAD = "HLOAD ", HALLOCATE = "HALLOCATE ";
   String MOVE = "MOVE ";
   String PRINT = "PRINT ";
   String TEMP = "TEMP ";
   String NOOP = "NOOP \n", ERROR = "ERROR ";
   String LE = "LE ",NE = "NE ",PLUS = "PLUS ",MINUS = "MINUS ",TIMES = "TIMES ",DIV = "DIV ";
   String endl = "\n",space = " ";

   Integer num = 1000;

   String gen_temp(){
      num++;
      return (TEMP + num.toString()+" ");
   }

   public boolean isTemp(String str){
      if(str.contains("TEMP")) return true;
      
      return false;
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      System.out.println(MAIN);
      n.f0.accept(this, argu);

      n.f1.accept(this, argu);
      System.out.println(END);

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   String printlabel = "prrrr";
   public R visit(StmtList n, A argu) {
      R _ret=null;
      n.f0.accept(this, (A)printlabel);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      
      System.out.println(n.f0.f0.toString() +" [" + n.f2.f0.toString() + "]");
      
      // n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // n.f3.accept(this, argu);
      System.out.println(BEGIN);
      String t1 = (String)n.f4.accept(this, argu);
      System.out.println(RETURN + t1);
      System.out.println(END);

      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      System.out.println(NOOP);
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      System.out.println(ERROR);
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      
      String t1 = (String)n.f1.accept(this, null);
      String l = n.f2.f0.toString();
      
      System.out.println(CJUMP + space + t1 + l);

      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      System.out.println(JUMP + space + n.f1.f0.toString());
      // n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;

      String t1 = (String)n.f1.accept(this, null);
      String i = n.f2.f0.toString();
      String t2 = (String)n.f3.accept(this, null);
      String new_t = gen_temp();
      System.out.println(MOVE + space + new_t + space + t2);
      System.out.println(HSTORE + space + t1 + space + i + space + new_t);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      // n.f1.accept(this, argu); //this prints Temp()

      String temp = TEMP + n.f1.f1.f0.toString() + space;

      String t1 = (String)n.f2.accept(this, null);
      
      String i = n.f3.f0.toString();
      System.out.println(HLOAD + temp + space + t1 + space + i);

      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      //n.f1.accept(this, argu); //this prints the temp value
      
      String t1 = (String)n.f2.accept(this, null);
      String temp = TEMP + n.f1.f1.f0.toString() + space;
      System.out.println(MOVE+ temp + space + t1);

      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;

      String t1 = (String)n.f1.accept(this, null);
      System.out.println(PRINT + t1);
      
      return _ret;
   }

   /**
    * f0 -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      A argu1 = argu;
      if(argu != null && argu.equals(firstchild)) argu1 = null;
      
      _ret = n.f0.accept(this, argu1);

      if(argu != null && argu.equals(firstchild)){
         String newt = gen_temp();
         System.out.println(MOVE + newt + (String)_ret);
         callStack.peek().add(newt);
         _ret = (R)newt;
      }
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;

      n.f0.accept(this, argu);
      n.f1.accept(this, null);
      n.f2.accept(this, argu);
      String t1 = (String)n.f3.accept(this, null);
      
      n.f4.accept(this, argu);
      
      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         callStack.peek().add(t1);
      }

      return (R)t1;
   }

   /**
    * f0 -> "CALL"
    * f1 -> Exp()
    * f2 -> "("
    * f3 -> ( Exp() )*
    * f4 -> ")"
    */
   Integer incall = 0;
   Stack<ArrayList<String>> callStack = new Stack<>();
   String firstchild = "firs";
   //"Call"
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      String t1 = (String)n.f1.accept(this, null);
      
      incall++;
      callStack.push(new ArrayList<>());

      n.f3.accept(this, (A)firstchild);
      
      ArrayList<String> curr_args = callStack.peek();
      callStack.pop();
      incall--;

      String newt = gen_temp();
      String code = MOVE + newt + endl;
      code += CALL + t1 + "( ";
      for(String t : curr_args){
         code += (t+" ");
      }
      code += ")";
      System.out.println(code);

      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         callStack.peek().add(newt);
      }

      return (R)newt;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;

      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, null);
      String newt = gen_temp();
      System.out.println(MOVE + newt + HALLOCATE+t1);
      
      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         callStack.peek().add(newt);
      }

      return (R)newt;
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);//it prints operator
      
      String t1 = (String)n.f1.accept(this, null);
      String t2 = (String)n.f2.accept(this, null);
      
      String new_t1 = gen_temp();
      System.out.println(MOVE + new_t1 + t1);
      
      String code = " "+n.f0.f0.choice.toString()+" "+new_t1+t2;
      
      String newt = gen_temp();
      System.out.println(MOVE + newt + code);

      _ret = (R)newt;
      
      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         callStack.peek().add(newt);
      }

      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      
      // System.out.print(space + n.f0.choice + space);
      // if(n.f0.choice.equals("LE")){
      //    System.out.println("LE");
      // }
      n.f0.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;

      String code = space+n.f0.toString()+space+n.f1.f0.toString()+space;

      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         callStack.peek().add(code);
      }
      
      return (R)code;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      
      R _ret=null;

      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         String newt = gen_temp();
         System.out.println(MOVE + newt + n.f0.toString());
         callStack.peek().add(newt);
      }

      _ret = (R)(space+n.f0.toString()+space);

      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      
      String str = (String)argu;
      if(argu!=null && str.equals(firstchild)){
         callStack.peek().add(n.f0.toString());
      }
      if(argu != null){
         if(argu instanceof String && argu.equals(printlabel))
            System.out.println(space+n.f0.toString()+space);
      }
      _ret = (R)(space+n.f0.toString()+space);
      return _ret;
   }

}
